name: Staging Server Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Ensure Environment File
        run: |
          if [ ! -f .env ]; then
            cp .env.example .env
          fi

      - name: Build Docker Image
        run: |
          docker compose build

      - name: Deploy Container
        run: |
          docker compose up -d --force-recreate --remove-orphans

      - name: Cleanup Unused Docker Images
        run: |
          docker system prune -f
